# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hitchens"
license = "MIT"
licenselink = "https://github.com/pimoore/theme-tufte/blob/main/LICENSE.md"
description = "A Micro.blog port of the Hitchens theme for Jekyll, by Pat Dryburgh"
homepage = "https://github.com/pimoore/theme-hitchens"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.20

[author]
name = "Pete Moore"
homepage = "https://pimoore.ca"